// For more info, see https://github.com/storybookjs/eslint-plugin-storybook#configuration-flat-config-format
import storybook from 'eslint-plugin-storybook'

import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import pluginQuery from '@tanstack/eslint-plugin-query'
import { defineConfig, globalIgnores } from 'eslint/config'
import { readdirSync } from 'node:fs'

// Dependencies go one way: app -> features -> shared (see README)
const FEATURES = readdirSync(new URL('./src/features', import.meta.url))
const restrict = (files, patterns) => ({
    files,
    // Tests and stories may reach into a feature's utils and fixtures
    ignores: ['**/*.test.{ts,tsx}', '**/*.stories.tsx'],
    rules: { 'no-restricted-imports': ['error', { patterns }] },
})
const IMPORT_LAYERS = [
    // The app goes through a feature's index.ts, never inside it
    restrict(
        ['src/app/**'],
        [
            {
                group: ['@/features/*/**'],
                message:
                    "Import from the feature's index.ts: '@/features/<name>'",
            },
        ]
    ),
    // A feature knows nothing of the app, nor of the other features
    ...FEATURES.map((feature) =>
        restrict(
            [`src/features/${feature}/**`],
            [
                {
                    group: ['@/app/**'],
                    message: 'A feature cannot import the app',
                },
                {
                    group: FEATURES.filter((f) => f !== feature).map(
                        (f) => `@/features/${f}`
                    ),
                    message:
                        'Features are independent: move what they share to src/shared/',
                },
            ]
        )
    ),
    // Shared code is used by everyone, so it depends on no one
    restrict(
        ['src/shared/**'],
        [
            {
                group: ['@/app/**', '@/features/**'],
                message: 'shared/ cannot import the app or a feature',
            },
        ]
    ),
]

export default defineConfig([
    globalIgnores([
        'dist',
        'coverage',
        'storybook-static',
        'playwright-report',
        'test-results',
        'public/mockServiceWorker.js', // generated by msw
    ]),
    ...pluginQuery.configs['flat/recommended'],
    {
        files: ['**/*.{ts,tsx}'],
        extends: [
            js.configs.recommended,
            tseslint.configs.recommended,
            reactHooks.configs.flat.recommended,
            reactRefresh.configs.vite,
        ],
        languageOptions: {
            globals: globals.browser,
            // One typescript-eslint is shared by every workspace: without this, an
            // editor linting several of them at once can't tell which root is ours
            parserOptions: { tsconfigRootDir: import.meta.dirname },
        },
        rules: {
            quotes: ['error', 'single', { avoidEscape: true }],
        },
    },
    ...IMPORT_LAYERS,
    ...storybook.configs['flat/recommended'],
])
